### ISSUE TITLE
Getting NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by dsdon10** [AppliedDataSciencePartners/DeepReinforcementLearning#1]

**Comment by dsdon10** [comment]
Running on:  https://c.onepanel.io/onepanel-demo/projects/alpha-zero-demo/code

**Comment by dsdon10** [comment]
Do you have a python 3 version?

**Comment by iandanforth** [comment]
This example requires python 2 for which xrange is not a built in function.

**Comment by zhouqiw** [comment]
~/anaconda3/lib/python3.6/site-packages/dask/dataframe/core.py in <module>()
     38 if PANDAS_VERSION >= '0.20.0':
     39     from pandas.util import cache_readonly
---> 40     pd.core.computation.expressions.set_use_numexpr(False)
     41 else:
     42     from pandas.util.decorators import cache_readonly

AttributeError: module 'pandas.core.computation' has no attribute 'expressions'

what are you environments?

**Comment by jbarrigapartarrieu** [comment]
I got the same issue. Apparently xrange is a function from Python 2. But when I was running Python 2, I could not install Tensorflow 1.4. Does that make sense?

**Comment by jbarrigapartarrieu** [comment]
I finally figured how to install Tensorflow 1.4 in my Python 2.7 environment.
However, now I am having a "protobuf" module missing issue, which cannot be installed in Python 2x because of an missing SSL certificate issue.
Have googled but to now avail. The error looks like this:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-255ae2e818f5> in <module>()
      8 import random
      9 
---> 10 from keras.utils import plot_model
     11 
     12 from game import Game, GameState

/Users/jbarrigapartarrieu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

/Users/jbarrigapartarrieu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/utils/__init__.py in <module>()
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 
      8 # Globally-importable utils.

/Users/jbarrigapartarrieu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/utils/conv_utils.py in <module>()
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

/Users/jbarrigapartarrieu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/backend/__init__.py in <module>()
     81 elif _BACKEND == 'tensorflow':
     82     sys.stderr.write('Using TensorFlow backend.\n')
---> 83     from .tensorflow_backend import *
     84 else:
     85     raise ValueError('Unknown backend: ' + str(_BACKEND))

/Users/jbarrigapartarrieu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py in <module>()
      3 from __future__ import print_function
      4 
----> 5 import tensorflow as tf
      6 from tensorflow.python.training import moving_averages
      7 from tensorflow.python.ops import tensor_array_ops

/Users/jbarrigapartarrieu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

/Users/jbarrigapartarrieu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     50 
     51 # Protocol buffers
---> 52 from tensorflow.core.framework.graph_pb2 import *
     53 from tensorflow.core.framework.node_def_pb2 import *
     54 from tensorflow.core.framework.summary_pb2 import *

/Users/jbarrigapartarrieu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py in <module>()
      4 import sys
      5 _b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
----> 6 from google.protobuf import descriptor as _descriptor
      7 from google.protobuf import message as _message
      8 from google.protobuf import reflection as _reflection

ImportError: No module named protobuf

**Comment by jdori** [comment]
I have a fork working on my local machine with at least Python 3.6.3 and 3.6.4: https://github.com/jdori/DeepReinforcementLearning

I'd be happy to clean up some if anyone thinks I should submit a PR

**Comment by NickShargan** [comment]
Just replace it by **range()**

**Comment by davidADSP** [comment]
Latest version is now Python3 compatible
